
version: '3.8'

services:
  db:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: fluxCartDB
    volumes:
      -  db:/var/lib/postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: matan@absprog.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - mynetwork

  app:
    image: flux-cart-app
    ports:
      - "1300:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
